apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-canary
  labels:
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        env: canary
    spec:
      containers:
      - name: hello-world
        image: quay.io/snsumner75/hello-world-instrumented:v1
        ports:
        - name: web
          containerPort: 5000
        - name: metrics
          containerPort: 8000
